### ISSUE TITLE
Unable to Artifact

### ISSUE THREAD

**Issue by rahulpatadiya** [miztiik/serverless-cloudwatch-log-retention#1]
I followed the step as you mention. We are using the Singapore region for the our AWS infra. I have created a bucket with the same region with Objects that can be public policy. 
I configured aws-cli with same region.  i am facing the error below. 

Unable to upload artifact ./src/cw-log-retention.py referenced by CodeUri parameter of CloudWatchLogRetentionFunction resource.
Parameter CodeUri of resource CloudWatchLogRetentionFunction refers to a file or folder that does not exist /Users/rahul/serverless-cloudwatch-log-retention/src/cw-log-retention.py

**Comment by miztiik** [comment]
This isn't an issue the code.

You code need to be put in `/Users/rahul/serverless-cloudwatch-log-retention/src/cw-log-retention.py`

Or update your relative path to pick up from the current location

**Comment by rahulpatadiya** [comment]
i have clone the repo. nothing to changed. 
/Users/rahul/serverless-cloudwatch-log-retention

├── README.md
├── helper_scripts
│   └── deploy.sh
├── images
│   └── miztiik-serverless-cloudwatch-log-retention-policy.png
├── outputs
├── serverless-cloudwatch-log-retention-policy.yaml
└── src
    └── cw-log-retention.sh

4 directories, 5 files

**Comment by miztiik** [comment]
Ah right, totally forgot. That code is not open sourced yet.

**Comment by rahulpatadiya** [comment]
Okay. Thank you! is it any possible for the code will be open source?
